server:
  port: 8080

spring:
  application:
    name: API-GATEWAY-4

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enable service discovery via Eureka
      
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/tasks/**

        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/projects/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**

        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/analytics/**

        - id: kanban-service
          uri: lb://KANBAN-SERVICE
          predicates:
            - Path=/kanban/**

        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comments/**

        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search/**

  security:
    oauth2:
      client:
        provider:
          github:
            user-name-attribute: name # Attribute name to use for OAuth2 user name
        registration:
          github:
            client-id: Ov23liM9U0xKPd4v9ddu # GitHub OAuth2 Client ID
            client-secret: 9c213b1e8e0af9be871c5fd09aae8a93481dc35d # GitHub OAuth2 Client Secret

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
